AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront HTTP and RTMP Distributions for Avalon
Parameters:
  StackName:
    Type: String
    Description: Name of the application stack (for tagging and naming)
  S3Bucket:
    Type: String
    Description: S3 bucket to the cfn deployment artifacts
  S3KeyPrefix:
    Description: S3 prefix to deployment artifacts
    Type: String
  TrustedSigner:
    Type: String
    Description: Trusted Signer ID for signing URLs
  PriceClass:
    Type: String
    Description: Price class of CloudFront distribution
  DerivativeBucket:
    Type: String
    Description: Bucket for Derivatives
  HostedZoneName:
    Type: String
    Description: Route53 zone to create an alias in
Resources:
  OAIFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        StackName: !Ref 'StackName'
        S3Bucket: !Ref 'S3Bucket'
        S3KeyPrefix: !Ref 'S3KeyPrefix'
        Package: 'cloudfront'
        Handler: 'oai'
        AllowedActions: 'cloudfront:*'
        Timeout: '10'
      TemplateURL: !Sub 'https://s3.amazonaws.com/${S3Bucket}/cloudformation/${S3KeyPrefix}/templates/lambdafunction.yaml'
  RTMPFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        StackName: !Ref 'StackName'
        S3Bucket: !Ref 'S3Bucket'
        S3KeyPrefix: !Ref 'S3KeyPrefix'
        Package: 'cloudfront'
        Handler: 'rtmp'
        AllowedActions: 'cloudfront:*'
        Timeout: '10'
      TemplateURL: !Sub 'https://s3.amazonaws.com/${S3Bucket}/cloudformation/${S3KeyPrefix}/templates/lambdafunction.yaml'
  CloudFrontOAI:
    Type: Custom::CloudFrontOAI
    Version: '1.0'
    DependsOn: "OAIFunction"
    DeletionPolicy: Retain
    Properties:
      ServiceToken: !GetAtt 'OAIFunction.Outputs.ServiceToken'
      Name: !Sub '${StackName}-cloudfront-oai'
  RTMPDistribution:
    Type: Custom::CloudFrontDistribution
    Version: '1.0'
    DeletionPolicy: Retain
    DependsOn: DerivativeBucketAccess
    Properties:
      ServiceToken: !GetAtt 'RTMPFunction.Outputs.ServiceToken'
      Name: !Sub '${StackName}-rtmp-distribution'
      PriceClass: !Ref 'PriceClass'
      DerivativeBucket: !Sub '${DerivativeBucket}.s3.amazonaws.com'
      TrustedSigner: !Ref 'TrustedSigner'
      CloudFrontRtmp: !Sub 'rtmpstream.${HostedZoneName}'
      CloudFrontOAI: !GetAtt 'CloudFrontOAI.Id'
  HTTPDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: DerivativeBucketAccess
    DeletionPolicy: Retain
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Sub '${DerivativeBucket}.s3.amazonaws.com'
          Id: !Sub '${StackName}-derivative-origin-hls'
          S3OriginConfig:
            OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI.Id}'
        Enabled: 'true'
        Comment: Avalon HTTP distribution
        DefaultRootObject: index.html
        Aliases:
        - !Sub 'httpstream.${HostedZoneName}'
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          TargetOriginId: !Sub '${StackName}-derivative-origin-hls'
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          TrustedSigners:
          - !Ref 'TrustedSigner'
          ViewerProtocolPolicy: allow-all
        PriceClass: !Ref 'PriceClass'
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'
  DerivativeBucketAccess:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref 'DerivativeBucket'
      PolicyDocument:
        Statement:
        - Effect: "Allow"
          Resource:
          - !Sub 'arn:aws:s3:::${DerivativeBucket}/*'
          Principal:
            CanonicalUser: !GetAtt 'CloudFrontOAI.S3CanonicalUserId'
          Action:
          - 's3:GetObject'
  HTTPRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: !Sub 'httpstream.${HostedZoneName}.'
      HostedZoneName: !Sub '${HostedZoneName}.'
      Type: CNAME
      TTL: '900'
      ResourceRecords:
        - !GetAtt 'HTTPDistribution.DomainName'
  RTMPRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: !Sub 'rtmpstream.${HostedZoneName}.'
      HostedZoneName: !Sub '${HostedZoneName}.'
      Type: CNAME
      TTL: '900'
      ResourceRecords:
        - !GetAtt 'RTMPDistribution.DomainName'
Outputs:
  OAI:
    Description: CloudFront OriginAccessIdentity
    Value: !Ref 'CloudFrontOAI'
  RTMP:
    Description: CloudFront RTMP Distribution
    Value: !Sub 'rtmp://${RTMPRecordSet}/'
  HTTP:
    Description: CloudFront RTMP Distribution
    Value: !Sub 'http://${HTTPRecordSet}/'
