AWSTemplateFormatVersion: '2010-09-09'
Description: Hydra fcrepo stack
Parameters:
  StackName:
    Type: String
    Description: Name of the ElasticBeanstalk environment
  ResourceName:
    Type: String
    Description: Name of the resource (for tagging)
    Default: fcrepo
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances
  SubnetID:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of an existing subnet IDs to use for the load balancer and auto
      scaling group
  S3Bucket:
    Type: String
    Description: S3 bucket with the Fcrepo war
  S3Key:
    Type: String
    Description: S3 key to the Fcrepo war
  MinSize:
    Type: Number
    Description: Minimum number of instances
  MaxSize:
    Type: Number
    Description: Maximum number of instances
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: A list of security groups, such as sg-a123fd85.
  LBSecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: A list of security groups, such as sg-a123fd85.
  HostedZoneName:
    Description: Route53 zone to create an alias in
    Type: String
  InstanceType:
    Type: String
    Description: The EC2 instance type
  RDSDatabaseName:
    Type: String
    Description: Database name
  RDSUsername:
    Type: String
    Description: Username for Database
  RDSPassword:
    Type: String
    Description: Password for Database
    NoEcho: 'true'
  RDSHostname:
    Type: String
    Description: Hostname for RDS Database
  RDSPort:
    Type: String
    Description: Database Port
  BinaryBucket:
    Type: String
    Description: S3 Bucket for Fedora's binary object store
  BinaryBucketKey:
    Type: String
    Description: AWS Access Key ID for binary object store
  BinaryBucketSecret:
    Type: String
    Description: AWS Secret Key for binary object store
Resources:
  FcrepoApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Sub '${StackName}-${ResourceName}'
      Description: Fcrepo service
  FcrepoApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref 'FcrepoApplication'
      Description: Fcrepo service version
      SourceBundle:
        S3Bucket: !Ref 'S3Bucket'
        S3Key: !Ref 'S3Key'
  FcrepoConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref 'FcrepoApplication'
      Description: Fcrepo configuration template
      OptionSettings:
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value: !Ref 'InstanceType'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: EC2KeyName
        Value: !Ref 'KeyName'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SSHSourceRestriction
        Value: tcp, 22, 22, 10.0.0.0/16
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SecurityGroups
        Value: !Join [ ',', !Ref 'SecurityGroups' ]
      - Namespace: aws:elb:loadbalancer
        OptionName: SecurityGroups
        Value: !Join [ ',', !Ref 'LBSecurityGroups' ]
      - Namespace: aws:elb:loadbalancer
        OptionName: CrossZone
        Value: 'true'
      - Namespace: aws:elb:policies
        OptionName: ConnectionDrainingEnabled
        Value: 'true'
      - Namespace: aws:ec2:vpc
        OptionName: ELBScheme
        Value: internal
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value: !Join [ ',', !Ref 'SubnetID' ]
      - Namespace: aws:ec2:vpc
        OptionName: ELBSubnets
        Value: !Join [ ',', !Ref 'SubnetID' ]
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: !Ref 'EC2InstanceProfile'
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: !Ref 'MinSize'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: !Ref 'MaxSize'
      - Namespace: aws:autoscaling:trigger
        OptionName: LowerBreachScaleIncrement
        Value: '0'
      - Namespace: aws:autoscaling:trigger
        OptionName: UpperBreachScaleIncrement
        Value: '0'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:elasticbeanstalk:container:tomcat:jvmoptions
        OptionName: Xmx
        Value: 2g
      - Namespace: aws:elasticbeanstalk:container:tomcat:jvmoptions
        OptionName: Xms
        Value: 2g
      - Namespace: aws:elasticbeanstalk:container:tomcat:jvmoptions
        OptionName: JVM Options
        Value: !Sub '-Duser.dir="/var/lib/fcrepo" -Dfcrepo.postgresql.host="${RDSHostname}"
          -Dfcrepo.postgresql.port="${RDSPort}" -Dfcrepo.postgresql.username="${RDSUsername}"
          -Dfcrepo.postgresql.password="${RDSPassword}" -Daws.accessKeyId="${BinaryBucketKey}"
          -Daws.secretKey="${BinaryBucketSecret}" -Daws.bucket="${BinaryBucket}" -Dfcrepo.modeshape.configuration="classpath:/config/jdbc-postgresql-s3/repository.json"'
      - Namespace: aws:elasticbeanstalk:application
        OptionName: Application Healthcheck URL
        Value: /rest
      - Namespace: aws:elb:listener:80
        OptionName: ListenerProtocol
        Value: HTTP
      SolutionStackName: 64bit Amazon Linux 2016.09 v2.5.3 running Tomcat 8 Java 8
  FcrepoEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref 'FcrepoApplication'
      Description: Fcrepo Environment
      EnvironmentName: !Sub '${StackName}-${ResourceName}'
      TemplateName: !Ref 'FcrepoConfigurationTemplate'
      VersionLabel: !Ref 'FcrepoApplicationVersion'
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
      - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref 'EC2Role'
  EBRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub '${ResourceName}.${HostedZoneName}'
      HostedZoneName: !Ref 'HostedZoneName'
      Type: CNAME
      TTL: '900'
      ResourceRecords:
      - !GetAtt 'FcrepoEnvironment.EndpointURL'
Outputs:
  URL:
    Description: URL of the AWS Elastic Beanstalk Environment
    Value: !Sub 'http://${EBRecordSet}/rest'
    Export:
      Name: !Sub '${StackName}-${ResourceName}-URL'
