AWSTemplateFormatVersion: '2010-09-09'
Description: Hydra public subzone and NS records
Parameters:
  SubZone:
    Description: Name for the new public subzone
    Type: String
  PublicZoneName:
    Description: Existing Route53 zone; used to create a public NS record for the
      new public subzone
    Type: String
Resources:
  PublicDNS:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub '${SubZone}.${PublicZoneName}.'
  PublicDNSNameServers:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub '${SubZone}.${PublicZoneName}.'
      HostedZoneName: !Sub '${PublicZoneName}.'
      Type: NS
      TTL: '900'
      ResourceRecords: !GetAtt 'PublicDNS.NameServers'
Outputs:
  PublicZoneName:
    Description: Name of the public subzone
    Value: !Sub '${SubZone}.${PublicZoneName}'
    Export:
      Name: !Sub '${SubZone}-dns-PublicZoneName'
