AWSTemplateFormatVersion: '2010-09-09'
Description: Hydra redis stack using ElastiCache
Parameters:
  StackName:
    Type: String
    Description: Name of the CloudFormation stack
  ResourceName:
    Type: String
    Description: Name of the resource (for tagging)
    Default: redis
  HostedZoneName:
    Description: Route53 zone to create an alias in
    Type: String
  SecurityGroups:
    Type: CommaDelimitedList
    Description: A list of security group ids, such as sg-a123fd85
  SubnetID:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of an existing subnet IDs to use for the load balancer and auto
      scaling group
  InstanceType:
    Type: String
    Description: The cache instance type
Resources:
  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: !Ref 'InstanceType'
      CacheSubnetGroupName: !Ref 'SubnetGroup'
      VpcSecurityGroupIds: !Ref 'SecurityGroups'
      Engine: redis
      NumCacheNodes: '1'
  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Cache Subnet Group
      SubnetIds: !Ref 'SubnetID'
  RedisRecordset:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub '${ResourceName}.${HostedZoneName}'
      HostedZoneName: !Ref 'HostedZoneName'
      Type: CNAME
      TTL: '900'
      ResourceRecords:
      - !GetAtt 'RedisCluster.RedisEndpoint.Address'
Outputs:
  EndpointAddress:
    Description: The Redis endpoint address
    Value: !Ref RedisRecordset
    Export:
      Name: !Sub '${StackName}-redis-EndpointAddress'
  EndpointPort:
    Description: The Redis endpoint port
    Value: !GetAtt 'RedisCluster.RedisEndpoint.Port'
    Export:
      Name: !Sub '${StackName}-redis-EndpointPort'
