AWSTemplateFormatVersion: '2010-09-09'
Description: Hydra travis/s3 artifact stack
Parameters:
  BucketName:
    Type: String
    Description: S3 Bucket of the deployment artifact
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref 'BucketName'
      AccessControl: PublicRead
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
        - Status: Enabled
          NoncurrentVersionExpirationInDays: 1
        - Status: Enabled
          Prefix: cloudformation/branch
          ExpirationInDays: 7
        - Status: Enabled
          Prefix: webapp/branch
          ExpirationInDays: 7
  S3User:
    Type: AWS::IAM::User
    Properties:
      Policies:
      - PolicyDocument:
          Statement:
          - Action: s3:*
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
        PolicyName: !Sub '${AWS::StackName}-S3Access'
  S3AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'S3User'
Outputs:
  IAMUser:
    Description: IAM User
    Value: !Ref 'S3User'
  AccessKeyId:
    Description: IAM Access Key for User
    Value: !Ref 'S3AccessKey'
  SecretAccessKey:
    Description: IAM Secret Access Key for User
    Value: !GetAtt 'S3AccessKey.SecretAccessKey'
  BucketName:
    Description: Name of newly created customer S3 bucket
    Value: !Ref 'S3Bucket'
