AWSTemplateFormatVersion: '2010-09-09'
Description: Hydra-in-a-Box zookeeper tier
Parameters:
  StackName:
    Type: String
    Description: Name of the ElasticBeanstalk environment
  ResourceName:
    Type: String
    Description: Name of the resource (for tagging)
    Default: zookeeper
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the EB instances
  MinSize:
    Type: Number
    Description: Minimum number of instances
    Default: 1
  MaxSize:
    Type: Number
    Description: Maximum number of instances
    Default: 6
  InstanceType:
    Type: String
    Description: The EC2 instance type
    Default: t2.micro
  HealthReportingSystemType:
    Type: String
    Description: Health reporting system
    AllowedValues: ['basic','enhanced']
    Default: 'enhanced'
  HostedZoneName:
    Description: Route53 zone to create an alias in
    Type: String
  S3Bucket:
    Type: String
    Description: Bucket with ZK source bundle
  S3Key:
    Type: String
    Description: Key for ZK source bundle
  SubnetID:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of an existing subnet IDs to use for the load balancer and auto
      scaling group
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: A list of security groups, such as sg-a123fd85.
  LBSecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: A list of security groups, such as sg-a123fd85.
Resources:
  ZKSharedConfigsBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref 'EC2Role'
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action: s3:*
            Effect: Allow
            Resource:
            - !Sub 'arn:aws:s3:::${ZKSharedConfigsBucket}/*'
            - !Sub 'arn:aws:s3:::${ZKSharedConfigsBucket}'
        PolicyName: !Sub '${AWS::StackName}-ZKS3Access'
  ZookeeperApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Sub '${StackName}-${ResourceName}'
      Description: Zookeeper application
  ZookeeperEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref 'ZookeeperApplication'
      Description: Zookeeper EB Environment
      EnvironmentName: !Sub '${AWS::StackName}-zookeeper'
      TemplateName: !Ref 'ZookeeperConfigurationTemplate'
      VersionLabel: !Ref 'ZKApplicationVersion'
      OptionSettings:
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: STACK_NAME
        Value: !Ref 'AWS::StackName'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: S3_BUCKET
        Value: !Ref 'ZKSharedConfigsBucket'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: S3_PREFIX
        Value: zookeeper
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: AWS_REGION
        Value: !Ref 'AWS::Region'
  ZookeeperConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref 'ZookeeperApplication'
      Description: Zookeeper configuration template
      OptionSettings:
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value: !Ref 'InstanceType'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: EC2KeyName
        Value: !Ref 'KeyName'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SSHSourceRestriction
        Value: tcp, 22, 22, 0.0.0.0/0
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SecurityGroups
        Value: !Join [',', !Ref 'SecurityGroups']
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: !Ref 'EC2InstanceProfile'
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: !Ref 'MinSize'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: !Ref 'MaxSize'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:elasticbeanstalk:command
        OptionName: DeploymentPolicy
        Value: Immutable
      - Namespace: aws:autoscaling:trigger
        OptionName: LowerThreshold
        Value: '10'
      - Namespace: aws:autoscaling:trigger
        OptionName: MeasureName
        Value: CPUUtilization
      - Namespace: aws:autoscaling:trigger
        OptionName: Statistic
        Value: Maximum
      - Namespace: aws:autoscaling:trigger
        OptionName: Unit
        Value: Percent
      - Namespace: aws:autoscaling:trigger
        OptionName: UpperThreshold
        Value: '90'
      - Namespace: aws:ec2:vpc
        OptionName: ELBScheme
        Value: internal
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value: !Join [ ',', !Ref 'SubnetID' ]
      - Namespace: aws:elb:loadbalancer
        OptionName: SecurityGroups
        Value: !Join [ ',', !Ref 'LBSecurityGroups' ]
      - Namespace: aws:elb:loadbalancer
        OptionName: CrossZone
        Value: 'true'
      - Namespace: aws:elb:listener
        OptionName: ListenerProtocol
        Value: HTTP
      - Namespace: aws:elb:listener
        OptionName: InstancePort
        Value: '8181'
      - Namespace: aws:elb:listener:2181
        OptionName: ListenerProtocol
        Value: TCP
      - Namespace: aws:elb:listener:2181
        OptionName: InstancePort
        Value: '2181'
      - Namespace: aws:autoscaling:updatepolicy:rollingupdate
        OptionName: RollingUpdateEnabled
        Value: 'true'
      - Namespace: aws:autoscaling:updatepolicy:rollingupdate
        OptionName: RollingUpdateType
        Value: Health
      - Namespace: aws:elasticbeanstalk:healthreporting:system
        OptionName: SystemType
        Value: !Ref 'HealthReportingSystemType'
      - Namespace: aws:elasticbeanstalk:application
        OptionName: Application Healthcheck URL
        Value: HTTP:8181/exhibitor/v1/ui/index.html
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: ServiceRole
        Value: aws-elasticbeanstalk-service-role
      - Namespace: aws:elasticbeanstalk:managedactions:platformupdate
        OptionName: UpdateLevel
        Value: minor
      - Namespace: aws:elasticbeanstalk:managedactions:platformupdate
        OptionName: InstanceRefreshEnabled
        Value: 'true'
      - Namespace: aws:elasticbeanstalk:managedactions
        OptionName: ManagedActionsEnabled
        Value: 'true'
      - Namespace: aws:elasticbeanstalk:managedactions
        OptionName: PreferredStartTime
        Value: Sun:00:00
      SolutionStackName: 64bit Amazon Linux 2016.09 v2.5.2 running Docker 1.12.6
  ZKApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref 'ZookeeperApplication'
      Description: Zookeeper service version
      SourceBundle:
        S3Bucket: !Ref 'S3Bucket'
        S3Key: !Ref 'S3Key'
  EBRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub '${ResourceName}.${HostedZoneName}'
      HostedZoneName: !Ref 'HostedZoneName'
      Type: CNAME
      TTL: '900'
      ResourceRecords:
      - !GetAtt 'ZookeeperEnvironment.EndpointURL'
Outputs:
  EndpointAddress:
    Value: !Sub '${EBRecordSet}:2181'
    Export:
      Name: !Sub '${StackName}-${ResourceName}-EndpointAddress'
  EnvironmentName:
    Value: !Ref 'ZookeeperEnvironment'
  URL:
    Description: URL of the AWS Elastic Beanstalk Environment
    Value: !Sub 'http://${EBRecordSet}/exhibitor/v1/ui/index.html'
    Export:
      Name: !Sub '${StackName}-${ResourceName}-URL'
